#+title: VladCV
#+author:    lynch513
#+email:     lynch513@yandex.ru

* CV
** Беспалов Владислав Александрович
*** Дата рождения: 15 января 2004

** Контакты:
*** Телефон: +7(911)1977810 (Telegram)
*** Email: VladislavBespalov2004@gmail.com
*** Адрес: Санкт-Петербург, ул

** Обо мне:
На данный момент являюсь студентом Санкт-Петербургского государственного университета аэрокосмического приборостроения. Интересуюсь программированием .Net и созданием игр на платформе Unity. Стремлюсь в будещем найти себя в бэкенд разработке на языке C#.

** Образование:
Санкт-Петербургский государственный университет аэрокосмического приборостроения. Кафедра инфокоммуникационных технологий и систем связи. Студент второго курса

** Навыки:
- опыт работы с С и C++
- опыт работы с C#
- понимание принципов ООП
- знание SOLID принципов
- умение работать с Git
- знание паттернов проектирования

** Личные качества:
Аналитический склад ума. Усидчивый и многозадачный, могу справиться с большим объемом информации. Любопытный перфекционист. Быстро учусь и имею большое желание работать по специальности. Хорошо взаимодействую с людьми, открытый, без проблем концентрируюсь на решении поставленных задач. У меня нет страха попросить помощи в решении какого-либо вопроса, если такие появляются.

** Иностранные языки:
Английский язык - базовые знания на уровне A1, понимание речи
